services:
  postgres:
    image: postgres:16
    container_name: fire-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fire
    ports:
      - "5432:5432"
    volumes:
      - fire_pg_data:/var/lib/postgresql/data

volumes:
  fire_pg_data:
